
spring.application.name=job-tracker

# Database (local)
spring.datasource.url=jdbc:postgresql://localhost:5432/jobtracker
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# App
server.port=8080

# JWT
jwt.secret=your-super-secret-key-which-should-be-very-long-at-least-256-bits
jwt.expiration=86400000

# Email (using Gmail)
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=madhumitha1205.1@gmail.com
spring.mail.password=lokhxffvnntbvshf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

