
spring.application.name=job-tracker
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/jobtracker
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# App
server.port=8080
# JWT
jwt.secret=your-super-secret-key-which-should-be-very-long-at-least-256-bits
jwt.expiration=86400000

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Queue names
app.rabbitmq.queue=status-update-queue
app.rabbitmq.exchange=status-update-exchange
app.rabbitmq.routing-key=status-update-key

# Email (using Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=madhumitha1205.1@gmail.com
spring.mail.password=kjmgjwxepqnltfvt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true